### ISSUE TITLE
Show image caption

### ISSUE THREAD

**Issue by Xirdion** [sowieso-web/contao-photoswipe-bundle#4]
The HTML for a caption container is already added to the lightbox.
```JavaScript
lightbox.on('uiRegister', function () {
    lightbox.pswp.ui.registerElement({
        name: 'caption', 
        order: 9, 
        isButton: false, 
        appendTo: 'root', 
        html: 'Caption text', 
        onInit: (el, pswp) => {
            lightbox.pswp.on('change', () => {
                const currSlideElement = lightbox.pswp.currSlide.data.element;
                let captionHTML = '';
                if (currSlideElement) {
                    const caption = currSlideElement.dataset.pswpCaption;
                    if (caption) {
                        captionHTML = caption;
                    } else {
                        captionHTML = currSlideElement.querySelector('img').getAttribute('alt');
                    }
                }
                el.innerHTML = captionHTML || '';
            });
        }
    });
});
```

**TODO:**
- [x] A styling for the caption (`.pswp--caption`) must be added to the page.

**Comment by Xirdion** [comment]
Following styling was added to the photoswipe.css file

```CSS
.pswp__caption {
    background: var(--pswp-icon-color-secondary);
    font-size: 16px;
    color: var(--pswp-icon-color);
    width: calc(100% - 32px);
    max-width: 400px;
    padding: 2px 8px;
    border-radius: 4px;
    position: absolute;
    left: 50%;
    bottom: 16px;
    transform: translateX(-50%);
}
```
